"""LLC-PC baseline adapted to the CoT-TP post-crash LC dataset."""

from .config import (
    DEFAULT_LAYOUT,
    DEFAULT_RENDER_CONFIG,
    NEIGHBOR_ROLES,
    DatasetLayout,
    EgoColumns,
    HistoryColumns,
    NeighborColumns,
    RenderConfig,
    dataset_layout_from_config,
    load_config,
    load_configured_split,
)
from .conditioning import ContextProjector, MotionQueryConditioner, MotionQueryInputs
from .context_index import QueryResult, TrainContextIndex
from .data_adapter import (
    ObservationSample,
    SampleValidationError,
    TrajectorySample,
    adapt_sample,
    load_mat_samples,
)
from .intention_points import IntentionPointKMeans, extract_future_endpoints
from .model import (
    LLCPCModelConfig,
    LLCPCMotionTransformer,
    ade_fde,
    llc_pc_loss,
    top1_trajectory,
)
from .prompt import build_prompt
from .schema import (
    AFFORDANCES,
    CONTEXT_DIM,
    INTENTIONS,
    SCENARIOS,
    ContextParseError,
    ParsedContext,
    encode_context,
    parse_llm_response,
)
from .tc_map import TCMapScene, VehicleTrace, build_tc_map_scene, render_tc_map_png
from .tensorizer import (
    AGENT_FEATURES,
    FeatureStandardizer,
    TensorizedBatch,
    TensorizedSample,
    TensorizerConfig,
    build_retrieval_features,
    standardizer_path_for_index,
    tensorize_sample,
    tensorize_samples,
)

__all__ = [
    "AFFORDANCES",
    "AGENT_FEATURES",
    "CONTEXT_DIM",
    "DEFAULT_LAYOUT",
    "DEFAULT_RENDER_CONFIG",
    "INTENTIONS",
    "NEIGHBOR_ROLES",
    "SCENARIOS",
    "ContextParseError",
    "ContextProjector",
    "DatasetLayout",
    "EgoColumns",
    "FeatureStandardizer",
    "HistoryColumns",
    "IntentionPointKMeans",
    "LLCPCModelConfig",
    "LLCPCMotionTransformer",
    "MotionQueryConditioner",
    "MotionQueryInputs",
    "NeighborColumns",
    "ObservationSample",
    "ParsedContext",
    "QueryResult",
    "RenderConfig",
    "SampleValidationError",
    "TCMapScene",
    "TensorizedBatch",
    "TensorizedSample",
    "TensorizerConfig",
    "TrajectorySample",
    "TrainContextIndex",
    "VehicleTrace",
    "adapt_sample",
    "ade_fde",
    "build_prompt",
    "build_retrieval_features",
    "build_tc_map_scene",
    "encode_context",
    "dataset_layout_from_config",
    "extract_future_endpoints",
    "load_mat_samples",
    "load_config",
    "load_configured_split",
    "llc_pc_loss",
    "parse_llm_response",
    "render_tc_map_png",
    "standardizer_path_for_index",
    "tensorize_sample",
    "tensorize_samples",
    "top1_trajectory",
]
