"""Train the MLP student that distills LLM strategy vectors from trajectories.

The student network implements the paper's teacher-student distillation step:
historical trajectory features are mapped to the CoT-derived strategy vector
previously generated by the LLM teacher.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import random
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
import scipy.io as sio
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, Subset


@dataclass(frozen=True)
class MatrixCols:
    """Column mapping used to construct trajectory-history features."""

    x: int
    y: int
    lon_v: int
    lat_v: int


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def convert_mat(value):
    if hasattr(value, "_fieldnames"):
        return {field: convert_mat(getattr(value, field)) for field in value._fieldnames}
    if isinstance(value, np.ndarray) and value.dtype == object:
        return [convert_mat(item) for item in value]
    return value


def load_mat_samples(path: Path, key: str) -> list[dict]:
    mat = sio.loadmat(str(path), struct_as_record=False, squeeze_me=True)
    if key not in mat:
        keys = [name for name in mat.keys() if not name.startswith("__")]
        raise KeyError(f"Key {key!r} not found in {path}. Available keys={keys}")
    data = convert_mat(mat[key])
    if isinstance(data, dict):
        return [data]
    return list(data)


def safe_np(value) -> Optional[np.ndarray]:
    if value is None:
        return None
    return np.asarray(value, dtype=np.float32)


def scalar_int(value, default: int = 0) -> int:
    try:
        return int(np.asarray(value).reshape(-1)[0])
    except Exception:
        return default


def neighbor_present(neigh_hist: np.ndarray, cols: MatrixCols, eps: float) -> bool:
    if neigh_hist is None or neigh_hist.size == 0:
        return False
    xy = neigh_hist[:, [cols.x, cols.y]]
    return bool(np.isfinite(xy).all() and np.any(np.abs(xy) > eps))


def pad_history(history: np.ndarray, history_len: int) -> np.ndarray:
    if history.shape[0] == history_len:
        return history
    padded = np.zeros((history_len, history.shape[1]), dtype=np.float32)
    rows = min(history_len, history.shape[0])
    padded[:rows] = history[:rows]
    return padded


def build_history_features(
    sample: dict,
    history_len: int,
    ego_cols: MatrixCols,
    neighbor_cols: MatrixCols,
    eps: float,
) -> np.ndarray:
    """Build the flattened history feature used by the MLP student."""

    status = scalar_int(sample.get("lane_status", 0))
    ctx = sample["ctx"]

    ego_full = safe_np(ctx["ego"])
    if ego_full is None:
        raise ValueError("Missing ego history")
    ego_hist = ego_full[:history_len, :]
    if ego_hist.shape[0] != history_len:
        raise ValueError("ego history length mismatch")

    ego_x = ego_hist[:, ego_cols.x]
    ego_y = ego_hist[:, ego_cols.y]
    ego_lon_v = ego_hist[:, ego_cols.lon_v]
    ego_lat_v = ego_hist[:, ego_cols.lat_v]

    x0, y0 = ego_x[0], ego_y[0]
    ego_feat = np.stack([ego_x - x0, ego_y - y0, ego_lon_v, ego_lat_v], axis=1).astype(np.float32)

    if status == 2:
        neighbor_keys = ["phys_ol", "phys_of", "phys_off"]
    else:
        neighbor_keys = ["phys_tl", "phys_tf", "phys_tff"]

    neighbor_features = []
    for key in neighbor_keys:
        neighbor = safe_np(ctx.get(key, None))
        if neighbor is None:
            neighbor_features.append(np.zeros((history_len, 4), dtype=np.float32))
            continue

        neighbor_hist = pad_history(neighbor[:history_len, :], history_len)
        if not neighbor_present(neighbor_hist, neighbor_cols, eps):
            neighbor_feat = np.zeros((history_len, 4), dtype=np.float32)
        else:
            neighbor_feat = np.stack(
                [
                    neighbor_hist[:, neighbor_cols.x] - ego_x,
                    neighbor_hist[:, neighbor_cols.y] - ego_y,
                    neighbor_hist[:, neighbor_cols.lon_v],
                    neighbor_hist[:, neighbor_cols.lat_v],
                ],
                axis=1,
            ).astype(np.float32)
        neighbor_features.append(neighbor_feat)

    return np.stack([ego_feat] + neighbor_features, axis=1).astype(np.float32).reshape(-1)


def load_teacher_vectors(vector_dir: Path) -> tuple[dict[int, np.ndarray], int]:
    ids_path = vector_dir / "ids.npy"
    vectors_path = vector_dir / "c.npy"
    if not ids_path.exists() or not vectors_path.exists():
        raise FileNotFoundError(f"Expected ids.npy and c.npy under {vector_dir}")
    ids = np.asarray(np.load(str(ids_path)), dtype=np.int64).reshape(-1)
    vectors = np.load(str(vectors_path)).astype(np.float32)
    if vectors.ndim != 2:
        raise ValueError(f"Teacher vectors must be a 2D array, got shape={vectors.shape}")
    if len(ids) != vectors.shape[0]:
        raise ValueError(f"Teacher ids/vector mismatch: ids={len(ids)} vectors={vectors.shape[0]}")
    if len(np.unique(ids)) != len(ids):
        raise ValueError(f"Teacher IDs must be unique under {vector_dir}")
    return {int(ids[i]): vectors[i] for i in range(len(ids))}, int(vectors.shape[1])


def require_vector_coverage(
    teacher_vectors: dict[int, np.ndarray], sample_count: int, split_name: str
) -> None:
    """Require one exact, zero-based teacher-vector ID for every MAT row in use."""

    missing = sorted(set(range(sample_count)) - set(teacher_vectors))
    if missing:
        preview = ", ".join(str(value) for value in missing[:10])
        raise ValueError(
            f"Missing {split_name} teacher vectors for zero-based MAT indices: {preview}"
        )


class DistillDataset(Dataset):
    def __init__(
        self,
        samples: list[dict],
        teacher_vectors: dict[int, np.ndarray],
        vector_dim: int,
        history_len: int,
        ego_cols: MatrixCols,
        neighbor_cols: MatrixCols,
        eps: float,
    ):
        self.samples = samples
        self.teacher_vectors = teacher_vectors
        self.vector_dim = vector_dim
        self.history_len = history_len
        self.ego_cols = ego_cols
        self.neighbor_cols = neighbor_cols
        self.eps = eps

    def __len__(self) -> int:
        return len(self.samples)

    def resolve_sample_id(self, idx: int, sample: dict) -> int:
        del sample
        if idx not in self.teacher_vectors:
            raise KeyError(f"No teacher vector found for zero-based MAT index {idx}")
        return idx

    def __getitem__(self, idx: int):
        sample = self.samples[idx]
        sample_id = self.resolve_sample_id(idx, sample)
        hist = build_history_features(sample, self.history_len, self.ego_cols, self.neighbor_cols, self.eps)
        target = self.teacher_vectors[sample_id]
        return (
            torch.tensor(hist, dtype=torch.float32),
            torch.tensor(target, dtype=torch.float32),
            torch.tensor(sample_id, dtype=torch.int32),
        )


def finite_indices(dataset: Dataset) -> tuple[list[int], list[tuple[int, str]]]:
    good = []
    bad = []
    for idx in range(len(dataset)):
        try:
            hist, target, sample_id = dataset[idx]
            ok = torch.isfinite(hist).all() and torch.isfinite(target).all()
        except Exception as exc:
            bad.append((idx, f"error:{exc}"))
            continue
        if ok:
            good.append(idx)
        else:
            bad.append((idx, f"sample_id:{int(sample_id)}"))
    return good, bad


def compute_hist_mean_std(dataset: Dataset, indices: list[int], hist_dim: int, eps: float) -> tuple[torch.Tensor, torch.Tensor]:
    count = 0
    sum_hist = torch.zeros(hist_dim, dtype=torch.float64)
    sum2_hist = torch.zeros(hist_dim, dtype=torch.float64)
    for idx in indices:
        hist, _, _ = dataset[idx]
        hist_d = hist.double()
        sum_hist += hist_d
        sum2_hist += hist_d * hist_d
        count += 1
    if count == 0:
        raise ValueError("No valid samples available for normalization")
    mean = (sum_hist / count).float()
    var = (sum2_hist / count - mean.double().pow(2)).clamp_min(eps).float()
    std = torch.sqrt(var).clamp_min(eps)
    return mean, std


class HistNormWrapper(Dataset):
    def __init__(self, base: Dataset, hist_mean: torch.Tensor, hist_std: torch.Tensor):
        self.base = base
        self.hist_mean = hist_mean
        self.hist_std = hist_std

    def __len__(self) -> int:
        return len(self.base)

    def __getitem__(self, idx: int):
        hist, target, sample_id = self.base[idx]
        return (hist - self.hist_mean) / self.hist_std, target, sample_id


class MLPStrategyStudent(nn.Module):
    """MLP student used to approximate the LLM teacher strategy vector."""

    def __init__(self, in_dim: int, hidden_dim: int, out_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, out_dim),
        )

    def forward(self, hist_norm: torch.Tensor) -> torch.Tensor:
        return self.net(hist_norm)


def write_json(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def env_int(name: str) -> Optional[int]:
    value = os.getenv(name)
    if value is None or value.strip() == "":
        return None
    return int(value)


def build_column_schemas(args: argparse.Namespace) -> tuple[Optional[MatrixCols], Optional[MatrixCols]]:
    required = [
        args.ego_x_col,
        args.ego_y_col,
        args.ego_lon_v_col,
        args.ego_lat_v_col,
        args.neighbor_x_col,
        args.neighbor_y_col,
        args.neighbor_lon_v_col,
        args.neighbor_lat_v_col,
    ]
    if any(value is None for value in required):
        return None, None

    return (
        MatrixCols(args.ego_x_col, args.ego_y_col, args.ego_lon_v_col, args.ego_lat_v_col),
        MatrixCols(args.neighbor_x_col, args.neighbor_y_col, args.neighbor_lon_v_col, args.neighbor_lat_v_col),
    )


def limit_samples(samples: list[dict], max_samples: Optional[int]) -> list[dict]:
    if max_samples is None or max_samples <= 0:
        return samples
    if len(samples) < max_samples:
        raise ValueError(f"Requested {max_samples} samples, but only {len(samples)} are available")
    return samples[:max_samples]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train the CoT-TP MLP StrategyStudent.")
    parser.add_argument("--train-mat", type=Path, required=True)
    parser.add_argument("--val-mat", type=Path, required=True)
    parser.add_argument("--test-mat", type=Path, required=True)
    parser.add_argument("--train-key", type=str, default="train_data")
    parser.add_argument("--val-key", type=str, default="validation_data")
    parser.add_argument("--test-key", type=str, default="test_data")
    parser.add_argument("--train-vector-dir", type=Path, required=True)
    parser.add_argument("--val-vector-dir", type=Path, required=True)
    parser.add_argument("--test-vector-dir", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("outputs/student_mlp"))
    parser.add_argument("--max-train-samples", type=int, default=None)
    parser.add_argument("--max-val-samples", type=int, default=None)
    parser.add_argument("--max-test-samples", type=int, default=None)
    parser.add_argument("--history-len", type=int, default=10)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=3e-6)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--lambda-cos", type=float, default=0.4)
    parser.add_argument("--eps", type=float, default=1e-6)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--ego-x-col", type=int, default=env_int("COTTP_EGO_X_COL"))
    parser.add_argument("--ego-y-col", type=int, default=env_int("COTTP_EGO_Y_COL"))
    parser.add_argument("--ego-lon-v-col", type=int, default=env_int("COTTP_EGO_LON_V_COL"))
    parser.add_argument("--ego-lat-v-col", type=int, default=env_int("COTTP_EGO_LAT_V_COL"))
    parser.add_argument("--neighbor-x-col", type=int, default=env_int("COTTP_NEIGHBOR_X_COL"))
    parser.add_argument("--neighbor-y-col", type=int, default=env_int("COTTP_NEIGHBOR_Y_COL"))
    parser.add_argument("--neighbor-lon-v-col", type=int, default=env_int("COTTP_NEIGHBOR_LON_V_COL"))
    parser.add_argument("--neighbor-lat-v-col", type=int, default=env_int("COTTP_NEIGHBOR_LAT_V_COL"))
    return parser.parse_args()


def resolve_device(device_arg: str) -> torch.device:
    if device_arg == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device_arg == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is not available")
    return torch.device(device_arg)


@torch.no_grad()
def evaluate_student(
    student: nn.Module,
    data_loader: DataLoader,
    device: torch.device,
    mse_loss: nn.Module,
    lambda_cos: float,
) -> dict[str, float]:
    student.eval()
    total_mse = 0.0
    total_cos = 0.0
    total_seen = 0

    for hist_norm, target, _ in data_loader:
        hist_norm = hist_norm.to(device)
        target = target.to(device)
        pred = student(hist_norm)
        loss_mse = mse_loss(pred, target)
        cos_sim = F.cosine_similarity(pred, target, dim=1).mean()
        batch_size = hist_norm.size(0)
        total_seen += batch_size
        total_mse += float(loss_mse) * batch_size
        total_cos += float(cos_sim) * batch_size

    if total_seen == 0:
        raise ValueError("Evaluation set contains no finite samples")

    mean_mse = total_mse / total_seen
    mean_cos = total_cos / total_seen
    return {
        "mse": mean_mse,
        "cos": mean_cos,
        "metric": mean_mse + lambda_cos * (1.0 - mean_cos),
        "num_samples": total_seen,
    }


def main() -> int:
    args = parse_args()
    if args.epochs <= 0:
        raise ValueError("--epochs must be positive")
    mat_paths = {args.train_mat.resolve(), args.val_mat.resolve(), args.test_mat.resolve()}
    if len(mat_paths) != 3:
        raise ValueError("Training, validation, and test MAT paths must be distinct")
    vector_paths = {
        args.train_vector_dir.resolve(),
        args.val_vector_dir.resolve(),
        args.test_vector_dir.resolve(),
    }
    if len(vector_paths) != 3:
        raise ValueError("Training, validation, and test vector directories must be distinct")
    set_seed(args.seed)
    device = resolve_device(args.device)
    ego_cols, neighbor_cols = build_column_schemas(args)
    if ego_cols is None or neighbor_cols is None:
        raise ValueError("Please provide all required ego and neighbor column mappings.")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    scaler_path = args.out_dir / "scaler_hist_for_distill.npz"
    best_ckpt_path = args.out_dir / "best_student_mlp.pth"
    strategy_ckpt_path = args.out_dir / "strategy_student_distill.pth"
    metrics_csv = args.out_dir / "epoch_metrics.csv"
    test_metrics_path = args.out_dir / "test_metrics.json"
    if test_metrics_path.exists():
        test_metrics_path.unlink()

    train_samples = limit_samples(load_mat_samples(args.train_mat, args.train_key), args.max_train_samples)
    val_samples = limit_samples(load_mat_samples(args.val_mat, args.val_key), args.max_val_samples)

    train_vectors, train_dim = load_teacher_vectors(args.train_vector_dir)
    val_vectors, val_dim = load_teacher_vectors(args.val_vector_dir)
    if train_dim != val_dim:
        raise ValueError(f"Teacher-vector dimension mismatch: train={train_dim}, val={val_dim}")
    vector_dim = train_dim
    require_vector_coverage(train_vectors, len(train_samples), "training")
    require_vector_coverage(val_vectors, len(val_samples), "validation")
    hist_dim = args.history_len * 4 * 4

    train_raw = DistillDataset(train_samples, train_vectors, vector_dim, args.history_len, ego_cols, neighbor_cols, args.eps)
    val_raw = DistillDataset(val_samples, val_vectors, vector_dim, args.history_len, ego_cols, neighbor_cols, args.eps)
    good_train, bad_train = finite_indices(train_raw)
    good_val, bad_val = finite_indices(val_raw)
    print(f"[filter] train good={len(good_train)} bad={len(bad_train)}")
    if bad_train:
        print("  train bad examples:", bad_train[:10])
    print(f"[filter] val good={len(good_val)} bad={len(bad_val)}")
    if bad_val:
        print("  val bad examples:", bad_val[:10])
    if not good_train or not good_val:
        raise ValueError("Training and validation sets must contain finite samples")

    hist_mean, hist_std = compute_hist_mean_std(train_raw, good_train, hist_dim, args.eps)
    np.savez(str(scaler_path), hist_mean=hist_mean.numpy(), hist_std=hist_std.numpy())

    train_ds = HistNormWrapper(train_raw, hist_mean, hist_std)
    val_ds = HistNormWrapper(val_raw, hist_mean, hist_std)
    train_loader = DataLoader(Subset(train_ds, good_train), batch_size=args.batch_size, shuffle=True, drop_last=False)
    val_loader = DataLoader(Subset(val_ds, good_val), batch_size=args.batch_size, shuffle=False, drop_last=False)

    student = MLPStrategyStudent(in_dim=hist_dim, hidden_dim=args.hidden_dim, out_dim=vector_dim).to(device)
    optimizer = torch.optim.Adam(student.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    mse_loss = nn.MSELoss()

    run_config = {
        "student_type": "mlp",
        "train_mat": str(args.train_mat),
        "val_mat": str(args.val_mat),
        "test_mat": str(args.test_mat),
        "train_vector_dir": str(args.train_vector_dir),
        "val_vector_dir": str(args.val_vector_dir),
        "test_vector_dir": str(args.test_vector_dir),
        "out_dir": str(args.out_dir),
        "num_train_samples": len(train_samples),
        "num_val_samples": len(val_samples),
        "good_train": len(good_train),
        "good_val": len(good_val),
        "history_len": args.history_len,
        "hist_dim": hist_dim,
        "strategy_vector_dim": vector_dim,
        "hidden_dim": args.hidden_dim,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "weight_decay": args.weight_decay,
        "lambda_cos": args.lambda_cos,
        "selection_split": "validation",
        "selection_metric": "mse_plus_cosine_loss",
        "seed": args.seed,
        "device": str(device),
        "ego_cols": ego_cols.__dict__,
        "neighbor_cols": neighbor_cols.__dict__,
    }
    write_json(args.out_dir / "run_config.json", run_config)

    best_val_metric = float("inf")
    best_payload = None
    fields = ["epoch", "train_mse", "train_cos", "train_metric", "val_mse", "val_cos", "val_metric", "best_val_metric"]
    with metrics_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()

        for epoch in range(1, args.epochs + 1):
            student.train()
            train_mse = 0.0
            train_cos = 0.0
            train_seen = 0
            for hist_norm, target, _ in train_loader:
                hist_norm = hist_norm.to(device)
                target = target.to(device)
                optimizer.zero_grad()
                pred = student(hist_norm)
                loss_mse = mse_loss(pred, target)
                cos_sim = F.cosine_similarity(pred, target, dim=1).mean()
                loss = loss_mse + args.lambda_cos * (1.0 - cos_sim)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(student.parameters(), max_norm=5.0)
                optimizer.step()

                batch_size = hist_norm.size(0)
                train_seen += batch_size
                train_mse += float(loss_mse.detach()) * batch_size
                train_cos += float(cos_sim.detach()) * batch_size

            train_mse /= train_seen
            train_cos /= train_seen
            train_metric = train_mse + args.lambda_cos * (1.0 - train_cos)

            val_metrics = evaluate_student(
                student,
                val_loader,
                device,
                mse_loss,
                args.lambda_cos,
            )
            val_mse = val_metrics["mse"]
            val_cos = val_metrics["cos"]
            val_metric = val_metrics["metric"]

            if val_metric < best_val_metric:
                best_val_metric = val_metric
                best_payload = {
                    "best_epoch": epoch,
                    "best_val_metric": float(best_val_metric),
                    "best_val_mse": float(val_mse),
                    "best_val_cos": float(val_cos),
                    "best_ckpt_path": str(best_ckpt_path),
                    "strategy_ckpt_path": str(strategy_ckpt_path),
                    "scaler_path": str(scaler_path),
                }
                torch.save(
                    {
                        "epoch": epoch,
                        "student_type": "mlp",
                        "state_dict": student.state_dict(),
                        "strategy_vector_dim": vector_dim,
                        "hist_dim": hist_dim,
                        "hist_mean": hist_mean.numpy(),
                        "hist_std": hist_std.numpy(),
                        "val_metric": best_val_metric,
                        "val_mse": val_mse,
                        "val_cos": val_cos,
                        "run_config": run_config,
                    },
                    best_ckpt_path,
                )
                shutil.copy2(best_ckpt_path, strategy_ckpt_path)
                write_json(args.out_dir / "best_metrics.json", best_payload)

            row = {
                "epoch": epoch,
                "train_mse": train_mse,
                "train_cos": train_cos,
                "train_metric": train_metric,
                "val_mse": val_mse,
                "val_cos": val_cos,
                "val_metric": val_metric,
                "best_val_metric": best_val_metric,
            }
            writer.writerow(row)
            f.flush()
            print(
                f"Epoch {epoch:03d} | "
                f"Train MSE={train_mse:.6f} cos={train_cos:.4f} metric={train_metric:.6f} | "
                f"Val MSE={val_mse:.6f} cos={val_cos:.4f} metric={val_metric:.6f}"
            )

    if best_payload is None or not best_ckpt_path.exists():
        raise RuntimeError("Training finished without a validation-selected checkpoint")

    checkpoint = torch.load(str(best_ckpt_path), map_location=device, weights_only=False)
    student.load_state_dict(checkpoint["state_dict"], strict=True)

    print("Loading the test set for one final evaluation")
    test_samples = limit_samples(load_mat_samples(args.test_mat, args.test_key), args.max_test_samples)
    test_vectors, test_dim = load_teacher_vectors(args.test_vector_dir)
    if test_dim != vector_dim:
        raise ValueError(f"Teacher-vector dimension mismatch: train={vector_dim}, test={test_dim}")
    require_vector_coverage(test_vectors, len(test_samples), "test")

    test_raw = DistillDataset(
        test_samples,
        test_vectors,
        vector_dim,
        args.history_len,
        ego_cols,
        neighbor_cols,
        args.eps,
    )
    good_test, bad_test = finite_indices(test_raw)
    print(f"[filter] test good={len(good_test)} bad={len(bad_test)}")
    if bad_test:
        print("  test bad examples:", bad_test[:10])
    if not good_test:
        raise ValueError("Test set must contain finite samples")

    test_ds = HistNormWrapper(test_raw, hist_mean, hist_std)
    test_loader = DataLoader(
        Subset(test_ds, good_test),
        batch_size=args.batch_size,
        shuffle=False,
        drop_last=False,
    )
    set_seed(args.seed)
    test_metrics = evaluate_student(
        student,
        test_loader,
        device,
        mse_loss,
        args.lambda_cos,
    )
    test_payload = {
        "checkpoint": str(best_ckpt_path),
        "selected_epoch": best_payload["best_epoch"],
        "selection_metric": "validation_mse_plus_cosine_loss",
        "selection_split": "validation",
        "evaluation_seed": args.seed,
        "test_evaluations": 1,
        "num_test_samples": len(test_samples),
        "good_test": len(good_test),
        "bad_test": len(bad_test),
        "test_mse": test_metrics["mse"],
        "test_cos": test_metrics["cos"],
        "test_metric": test_metrics["metric"],
    }
    write_json(test_metrics_path, test_payload)

    run_config.update(
        {
            "num_test_samples": len(test_samples),
            "good_test": len(good_test),
            "bad_test": len(bad_test),
            "test_evaluations": 1,
        }
    )
    write_json(args.out_dir / "run_config.json", run_config)

    print("Student distillation completed.")
    print(
        f"Final test | MSE={test_metrics['mse']:.6f} "
        f"cos={test_metrics['cos']:.4f} metric={test_metrics['metric']:.6f}"
    )
    print(f"Final test metrics saved to {test_metrics_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
